### ISSUE TITLE
Layout issues with Firefox

### ISSUE THREAD

**Issue by js-robinson** [webappsforengineers/wa4e-v2#2] opened 2021-11-17 08:55 UTC
Firefox 94.0
Linux Mint 20.2
1920x1080

![Screenshot from 2021-11-17 08-40-16](https://user-images.githubusercontent.com/4589392/142168295-80baff49-c86d-43a7-b190-bc3619ffdc6c.png)

**Comment by PipGrylls** [comment] 2021-11-17 10:26
Fixed by limiting columns to 4 at all breakpoints. This was likely caused by firefox and chromium enforcing styles in different orders.

**Closed by PipGrylls** 2021-11-17 10:26 UTC
Labels: bug
